image:
  pullPolicy: Always
ingress:
  enabled: true
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
  tls:
    - hosts:
        - ${host}
      secretName: ixo-minerva-oracle-tls
  hosts:
    - host: ${host}
      paths:
        - path: /
          pathType: Prefix
env:
  - name: NODE_ENV
    value: "production"
  - name: DATABASE_USE_SSL
    value: "true"
  - name: PORT
    value: "4563"
  - name: MATRIX_BASE_URL
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#MATRIX_BASE_URL>"
  - name: "MATRIX_ORACLE_ADMIN_ACCESS_TOKEN"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#MATRIX_ORACLE_ADMIN_ACCESS_TOKEN>"
  - name: MATRIX_ORACLE_ADMIN_PASSWORD
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#MATRIX_ORACLE_ADMIN_PASSWORD>"
  - name: "MATRIX_ORACLE_ADMIN_USER_ID"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#MATRIX_ORACLE_ADMIN_USER_ID>"
  - name: "MATRIX_RECOVERY_PHRASE"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#MATRIX_RECOVERY_PHRASE>"
  - name: "OPENAI_API_KEY"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#OPENAI_API_KEY>"
  - name: "LANGFUSE_PUBLIC_KEY"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#LANGFUSE_PUBLIC_KEY>"
  - name: "LANGFUSE_SECRET_KEY"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#LANGFUSE_SECRET_KEY>"
  - name: "LANGFUSE_HOST"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#LANGFUSE_HOST>"
  - name: "OPEN_ROUTER_API_KEY"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#OPEN_ROUTER_API_KEY>"
  - name: "SUBSCRIPTION_ORACLE_MCP_URL"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#SUBSCRIPTION_ORACLE_MCP_URL>"
  - name: "RPC_URL"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#RPC_URL>"
  - name: "BLOCKSYNC_GRAPHQL_URL"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#BLOCKSYNC_GRAPHQL_URL>"
  - name: "LIVE_AGENT_AUTH_API_KEY"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#LIVE_AGENT_AUTH_API_KEY>"
  - name: "SECP_MNEMONIC"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#SECP_MNEMONIC>"
  - name: "ORACLE_NAME"
    value: "minerva"
  - name: "ORACLE_ENTITY_DID"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#ORACLE_ENTITY_DID>"
  - name: "MEMORY_MCP_URL"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#MEMORY_MCP_URL>"
  - name: "MEMORY_MCP_API"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#MEMORY_MCP_API>"
  - name: "MEMORY_ENGINE_URL"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#MEMORY_ENGINE_URL>"
  - name: "MEMORY_SERVICE_API_KEY"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#MEMORY_SERVICE_API_KEY>"
  - name: "ORACLE_API_KEY"
    value: "<path:${vault_mount}/data/ixo-minerva-oracle#ORACLE_API_KEY>"
service:
  port: 4563
resources:
  requests:
    memory: 250Mi
    cpu: "50m"
  limits:
    memory: 350Mi
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 1
  targetMemoryUtilizationPercentage: "30"