neo4j:
  name: '${org}-neo4j'
  password: "${password}"
  acceptLicenseAgreement: "yes"
  resources:
    cpu: 500m
    memory: 2Gi

# SSL/TLS configuration for Bolt protocol
ssl:
  bolt:
    privateKey:
      secretName: neo4j-tls
      subPath: tls.key
    publicCertificate:
      secretName: neo4j-tls
      subPath: tls.crt
    trustedCerts:
      sources: []

config:
  dbms.connector.bolt.enabled: "true"
  dbms.connector.bolt.tls_level: "OPTIONAL"
  server.bolt.tls_level: "OPTIONAL"

volumes:
  data:
    mode: 'dynamic'
    dynamic:
      storageClassName: '${storage_class}'
      accessModes:
        - ReadWriteOnce
      requests:
        storage: ${storage_size}